//Search
enum EApplyTypes
// Add at the END of the enum
#ifdef ENABLE_ANTI_RESISTANTS
			APPLY_ATTBONUS_SWORD,
			APPLY_ATTBONUS_TWOHAND,
			APPLY_ATTBONUS_DAGGER,
			APPLY_ATTBONUS_BELL,
			APPLY_ATTBONUS_FAN,
			APPLY_ATTBONUS_BOW,
			APPLY_ATTBONUS_CLAW,
#endif