//search
case POINT_NORMAL_HIT_DEFEND_BONUS:
//Add After
#ifdef ANTI_RESISTANTS
		case POINT_ATTBONUS_SWORD:
		case POINT_ATTBONUS_TWOHAND:
		case POINT_ATTBONUS_DAGGER:
		case POINT_ATTBONUS_BELL:
		case POINT_ATTBONUS_FAN:
		case POINT_ATTBONUS_BOW:
		case POINT_ATTBONUS_CLAW:
#endif

//search
case APPLY_RESIST_CLAW:
//Add After
#ifdef ANTI_RESISTANTS
		case APPLY_ATTBONUS_SWORD:
		case APPLY_ATTBONUS_TWOHAND:
		case APPLY_ATTBONUS_DAGGER:
		case APPLY_ATTBONUS_BELL:
		case APPLY_ATTBONUS_FAN:
		case APPLY_ATTBONUS_BOW:
		case APPLY_ATTBONUS_CLAW:
#endif