//Search
const TApplyInfo aApplyInfo[MAX_APPLY_NUM]
//at the END of the definition add
#ifdef ANTI_RESISTANTS
	{POINT_ATTBONUS_SWORD,},
	{POINT_ATTBONUS_TWOHAND,},
	{POINT_ATTBONUS_DAGGER,},
	{POINT_ATTBONUS_BELL,},
	{POINT_ATTBONUS_FAN,},
	{POINT_ATTBONUS_BOW,},
	{POINT_ATTBONUS_CLAW,},
#endif

//Search
{NULL, 0}
//add BEFORE
#ifdef ANTI_RESISTANTS
	{"ATTBONUS_SWORD", APPLY_ATTBONUS_SWORD},
	{"ATTBONUS_TWOHAND", APPLY_ATTBONUS_TWOHAND},
	{"ATTBONUS_DAGGER", APPLY_ATTBONUS_DAGGER},
	{"ATTBONUS_BELL", APPLY_ATTBONUS_BELL},
	{"ATTBONUS_FAN", APPLY_ATTBONUS_FAN},
	{"ATTBONUS_BOW", APPLY_ATTBONUS_BOW},
	{"ATTBONUS_CLAW", APPLY_ATTBONUS_CLAW},
#endif