//Search
MAX_APPLY_NUM,
//Add BEFORE
#ifdef ANTI_RESISTANTS
	APPLY_ATTBONUS_SWORD,
	APPLY_ATTBONUS_TWOHAND,
	APPLY_ATTBONUS_DAGGER,
	APPLY_ATTBONUS_BELL,
	APPLY_ATTBONUS_FAN,
	APPLY_ATTBONUS_BOW,
	APPLY_ATTBONUS_CLAW,
#endif